# Transform from flat drawing to 3D drawing plane
geometry_msgs/Transform transform

# 2D vertices to draw
avatar_challenge_msgs/Point2D[] points

---
# Result
bool success

# Result status message
string message

# Duration of action
float32 duration

---
# Internal state of drawing
string state
